language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install.sh wordpress_test root '' localhost $WP_VERSION
  # - bash tests/bin/travis.sh before

script: phpunit -c phpunit.xml

after_script:
  # - bash tests/bin/travis.sh after
