language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - export WP_DEVELOP_DIR=/tmp/wordpress-tests-lib
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # Install CodeSniffer for WordPress Coding Standards checks.
  - mkdir php-codesniffer && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C php-codesniffer
  # Install WordPress Coding Standards.
  - mkdir wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards
  # Hop into CodeSniffer directory.
  - cd php-codesniffer
  # Set install path for WordPress Coding Standards
  - scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash
  - cd ..
  - pwd
  - whereis phpcs
  - phpcs -i


script: 
  - phpunit -c phpunit.xml
  - $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php

after_script:
  # - bash tests/bin/travis.sh after
